### ISSUE TITLE
Add note to docs about svelte-transition 

### ISSUE THREAD

**Issue by CaptainCodeman** [CaptainCodeman/svelte-headlessui#43]
Make it clear that `svelte-transition` is a separate package that needs to be installed if you want to use it in your own component (as shown in the examples).

It's not a dependency of `svelte-headlessui` itself, although it may be worth considering adding it to this package (as it will likely be used more often than not).

**Comment by colinbate** [comment]
When I installed `svelte-headlessui`, the `svelte-transition` came with it. It is listed as a dependency in here: https://github.com/CaptainCodeman/svelte-headlessui/blob/master/packages/lib/package.json

That said, I agree that it doesn't need to be a dependency. I didn't use it myself because it gave me issues with SSR in SvelteKit.
