### ISSUE TITLE
Multiple selection for ListBox

### ISSUE THREAD

**Issue by thanhtschoepe** [CaptainCodeman/svelte-headlessui#56]
Hi! Is support for multiple selection on the road map? Thank you for keeping up to date! I'm on the camp of moving from [rgossiaux](https://github.com/rgossiaux/svelte-headlessui/commits?author=rgossiaux)

**Comment by CaptainCodeman** [comment]
Like the one discussed here https://github.com/CaptainCodeman/svelte-headlessui/issues/49, or something different?

I think the other approach would be to have each listbox item be a checkbox, but the chips provide the display of what is selected when the dropdown isn't open which would otherwise be lost. Otherwise, for good UI, I'd usually want to use an always-open list or two lists that things move betweem
