### ISSUE TITLE
Tab Transition?

### ISSUE THREAD

**Issue by sideshot** [CaptainCodeman/svelte-headlessui#91]
Any thoughts on the best way to have the tabs be a smooth transition?

**Comment by CaptainCodeman** [comment]
This would probably depend on if it's used for navigation in which case I'd look at the page transition API - there are some articles on how to do that with SvelteKit. It may still be usable for other things, I haven't tried it enough myself, but otherwise I'd personally be looking into what Tailwind solutions exist for that kind of animation (I think I've seen some but can't remember where off-hand). Likewise if you're using some other styling system, I'd start looking in their ecosystem and go from there.
